/*****************************************************************************
 **  Cobi    http://www.scalasca.org/                                       **
 *****************************************************************************
 **  Copyright (c) 2009-2010                                                **
 **  Forschungszentrum Juelich, Juelich Supercomputing Centre               **
 **                                                                         **
 **  See the file COPYRIGHT in the base directory for details               **
 *****************************************************************************/

/**
 * @file   codeparsertest.h
 * @author Jan Mussler
 * @brief Codeparser Test class definition
 */

#include "snippetfactories.h"

#ifndef CODEPARSERTEST_H
#define	CODEPARSERTEST_H

namespace gi {
    namespace generator {
        namespace parser {

            /**
             * tests for codeparser
             */
            class CodeParserTest {
            private:
                static bool test(std::string code, bool result);
            public:
                CodeParserTest();
                ~CodeParserTest();

                /**
                 * test parser using correct and incorrect statements
                 */
                static void syntaxTest();

                /**
                 * user readable output of AST tree generated by parser
                 */
                static void treeOutputTest();
            };
        }
    }
}

#endif	/* CODEPARSERTEST_H */

